version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ts_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: unless-stopped
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
    driver: local
