import { useEffect, useState, type FormEvent } from "react";
import type { OutlineNode, OutlineNodeType, OutlineStatus } from "../entities/outline";
import type { LibraryGateway } from "../shared/api/libraryGateway";
const typeLabels:Record<OutlineNodeType,string>={planning:"規劃節點",volume:"卷／部",chapter:"章節",scene:"場景"};
const statusLabels:Record<OutlineStatus,string>={idea:"構想",planned:"已規劃",drafting:"撰寫中",revising:"修訂中",done:"完成"};
export function OutlineWorkspace({workId,gateway,onError,onStructureChanged}:{workId?:string;gateway:LibraryGateway;onError(message:string):void;onStructureChanged():Promise<void>}) {
  const [nodes,setNodes]=useState<OutlineNode[]>([]),[showForm,setShowForm]=useState(false),[editingId,setEditingId]=useState<string>();
  const [title,setTitle]=useState(""),[nodeType,setNodeType]=useState<OutlineNodeType>("planning"),[status,setStatus]=useState<OutlineStatus>("idea"),[parentId,setParentId]=useState(""),[summary,setSummary]=useState(""),[purpose,setPurpose]=useState(""),[conflict,setConflict]=useState(""),[outcome,setOutcome]=useState(""),[notes,setNotes]=useState("");
  useEffect(()=>{if(!workId){setNodes([]);return;}gateway.listOutlineNodes(workId).then(setNodes).catch(()=>onError("無法讀取結構大綱。"));},[gateway,onError,workId]);
  function reset(){setShowForm(false);setEditingId(undefined);setTitle("");setNodeType("planning");setStatus("idea");setParentId("");setSummary("");setPurpose("");setConflict("");setOutcome("");setNotes("");}
  function edit(node:OutlineNode){setEditingId(node.id);setTitle(node.title);setNodeType(node.nodeType);setStatus(node.status);setParentId(node.parentId??"");setSummary(node.summary);setPurpose(node.purpose);setConflict(node.conflict);setOutcome(node.outcome);setNotes(node.notes);setShowForm(true);}
  async function submit(event:FormEvent){event.preventDefault();if(!workId||!title.trim())return;try{const node=await gateway.saveOutlineNode({id:editingId,workId,parentId:parentId||undefined,nodeType,title,status,summary,purpose,conflict,outcome,notes});setNodes(current=>editingId?current.map(item=>item.id===node.id?node:item):[...current,node]);reset();}catch{onError("無法保存大綱節點；標題是唯一必填欄位。");}}
  async function convert(node:OutlineNode){if(!workId)return;try{const updated=await gateway.convertOutlineNodeToChapter(workId,node.id);setNodes(current=>current.map(item=>item.id===updated.id?updated:item));await onStructureChanged();}catch{onError("無法轉成章節；節點可能已綁定或不適合轉換。");}}
  return <main className="outline-pane"><header className="cards-header"><div><span className="eyebrow">選用規劃工具</span><h2>結構大綱</h2><p>可以先規劃、稍後才建立或綁定正文。</p></div><button className="button button--primary" disabled={!workId} onClick={()=>setShowForm(true)}>＋ 新增節點</button></header>
    {!workId?<div className="editor-empty"><h2>請先選擇作品</h2></div>:<div className="outline-content">{showForm&&<form className="outline-form" onSubmit={submit} aria-label={editingId?"編輯大綱節點":"建立大綱節點"}><div className="form-heading"><h3>{editingId?"編輯規劃":"新增規劃"}</h3><button type="button" className="icon-button" aria-label="關閉" onClick={reset}>×</button></div><label>標題 <span>唯一必填</span><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>節點類型<select value={nodeType} onChange={e=>setNodeType(e.target.value as OutlineNodeType)}>{Object.entries(typeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>狀態<select value={status} onChange={e=>setStatus(e.target.value as OutlineStatus)}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>上層節點<select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">最上層</option>{nodes.filter(node=>node.id!==editingId).map(node=><option key={node.id} value={node.id}>{node.title}</option>)}</select></label>{[["摘要",summary,setSummary],["目的",purpose,setPurpose],["衝突",conflict,setConflict],["結果",outcome,setOutcome],["作者備註",notes,setNotes]].map(([label,value,setter])=><label className="field-wide" key={label as string}>{label as string}<textarea value={value as string} onChange={e=>(setter as (value:string)=>void)(e.target.value)}/></label>)}<p className="form-note field-wide">規劃節點不必綁定章節或場景，也不會自動建立正文。</p><div className="form-actions"><button type="button" className="button button--quiet" onClick={reset}>取消</button><button className="button button--primary" disabled={!title.trim()}>{editingId?"儲存修改":"建立節點"}</button></div></form>}
      {nodes.length?<ol className="outline-list">{nodes.map(node=><li key={node.id} style={{marginLeft:node.parentId?24:0}}><div className="outline-node"><button className="outline-node-main" onClick={()=>edit(node)}><span className="outline-type">{typeLabels[node.nodeType]}</span><strong>{node.title}</strong><small>{statusLabels[node.status]}{node.boundEntityId?" · 已綁定正文":" · 尚未綁定"}</small>{node.summary&&<p>{node.summary}</p>}</button>{!node.boundEntityId&&node.nodeType!=="volume"&&<button className="button button--outline outline-convert" onClick={()=>convert(node)}>轉成章節</button>}</div></li>)}</ol>:!showForm&&<div className="empty-state"><div className="empty-glyph">綱</div><h2>大綱是選用的</h2><p>可直接寫正文，也可以先放一個尚未綁定的想法。</p><button className="button button--primary" onClick={()=>setShowForm(true)}>建立第一個規劃節點</button></div>}
    </div>}</main>;
}
